import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Olá Mundo</h1>

      <Link href="/Jogos" passHref>
        <span className={styles.span}>Ir para jogos</span>
      </Link>

      <a href="/Jogos">Ir para jogos</a>
    </div>
  )
}

export default Home
